### PR TITLE
Added support for readin menus as JSON from rest api

### PR DESCRIPTION
**Pull request by ishaan-puniani**
Added support for reading menus using https://wordpress.org/plugins/wp-api-menus/ plugin

### CODE REVIEW

**Comment by kadamwhite** [comment]
Thanks for this! I will review this week, apologies on the delay in response.

**Comment by kadamwhite** [comment]
@ishaan-puniani Apologies for the delay, but I'll be working on this library heavily for the coming week. This logic may be superseded by the auto-discovery work I have in progress, but I will not close this until I've validated that auto-generated routes fully replace this functionality, and I sincerely appreciate the PR! It would have been merged two months ago had we not been in the middle of refactoring the internals of this library.

**Comment by kadamwhite** [comment]
@ishaan-puniani With the latest v0.8 release, this functionality can be achieved by leveraging the auto-discovery capabilities of the client: To bind a WP API client instance to the API-enabled WordPress site "yoursite.com", running the menus plugin, this code will permit the use of the same `.menus()` and `.menuLocations()` methods without having to define any custom classes:

```js
// Use auto-discovery to bind an API client isntance
var ready = WP.discover( 'http://yoursite.com' ).then(function( site ) {
	// Create shortcuts to the menus resource handlers
	site.menus = site.namespace( 'wp-api-menus/v2' ).menus;
	site.menuLocations = site.namespace( 'wp-api-menus/v2' )[ 'menu-locations' ];
});

// Once the WP client has completed discovery and has been customized
// with the menu methods, it can be used as normal:
ready.then(function(site) {
	// Request and log the available menus and menu locations
	site.menus().then(results => console.log( results ) );
	site.menuLocations().then(results => console.log( results ) );
});
```

**Comment by ishaan-puniani** [comment]
That is very helpful. 
I will try it. Thanks

**Pull request closed without merging**
