### PR TITLE
JWT auth option added

### PR DESCRIPTION
**Pull request by Matthewnie**
Added in the option to use JSON Web Tokens for authorization

### CODE REVIEW

**Comment by anagio** [comment]
@bmac are you able to merge this? I was just about to submit the same option for JWT!

**Comment by kadamwhite** [comment]
I will review this afternoon, thanks for bumping the issue!

**Comment by kadamwhite** [comment]
Apologies for the lack of movement on this, I've been reviewing potential alternatives. At present we are leaning towards providing a `.setHeaders()` method that can be used to specify this header for one or more request instances without requiring a special case for JWT authentication throughout the codebase.

What this would provisionally look like would be this:

```js
var wp = WPAPI.site( 'http://mysite.com/wp-json' );
wp.setHeaders( 'Authorization', 'Bearer ' + options.jwt );
wp.users().me()...
```

**Comment by kadamwhite** [comment]
The aforementioned alternative implementation is now available for review as pull request #315 -- @anagio @Matthewnie I would welcome your feedback on this new interface

**Pull request closed without merging**
